### ISSUE TITLE
关于 categories 目录下的问题

### ISSUE THREAD

**Issue by ghosthim** [isecret/Hola#4]
在任意[文章分类页面]无法跳转到指定的[文章页面]，包括分类页面底部的翻页按钮也会默认跳转到首页。
例如，我博客下的一个分类 [https://blog.api2u.me/categories/Blog](https://blog.api2u.me/categories/Blog) ，无论是该页面的哪个文章都会默认跳转到首页 / .

**Comment by isecret** [comment]
我重现了这个问题，不仅在 分类 下会有这个情况，在 标签 下也出现了这个情况，我去翻翻文档名看看问题出在什么地方了，修好了会 @ 你。

**Comment by ghosthim** [comment]
问题找到了，category.ejs文件中的7 8 11 行的 article.link 变量貌似没寻到导致返回 / 的地址，改成官方变量文档中的 article.path 后问题就会解决, tag 页面当然也是同样的方法。

**Comment by ghosthim** [comment]
不过奇怪的是问题的 分类 标签 页面点击文章是跳转首页时并没有 target="_blank" 属性，而这一属性在更换 article.path 后就会有了，不知道哪里的问题，如果 article.link 没定义的话应该会报错啊，这就不太懂了。
