### ISSUE TITLE
gitment无法正常初始化

### ISSUE THREAD

**Issue by duskdusts** [isecret/Hola#6]
我github登陆之后就是object ProgressEvent,然后一直loading，无法正常使用。

**Comment by isecret** [comment]
我看了一下你站点，你似乎没有正确的绑定 callback 回调地址，然后跳转会首页了，你修改一下看看？

**Comment by duskdusts** [comment]
呃,是这个吗？https://again.now.sh

**Comment by duskdusts** [comment]
![Screenshot_2020-09-14-13-39-13-124_com microsoft emmx](https://user-images.githubusercontent.com/60814886/93047755-c2f7d700-f68f-11ea-9d0b-1a769f02e79b.jpg)
就是这样#@#

**Comment by duskdusts** [comment]
大佬，我是一个小白，能告诉我如何把这个评论区删去吗？

**Comment by isecret** [comment]
我定位到问题了，刚刚提交了更新，你可以尝试重新 clone 或者 下载模版。这个问题是因为 Gitment 的授权服务器关掉了，我自己架设了一个站点。另外关于关闭评论的话我之前没有考虑到，你可以尝试删除/注释插件来实现，文件路径：`Hola/blob/master/layout/layout.ejs`，注释 `125` 行代码，如下：

```javascript
// gitment.render("gitment");
```

**Comment by duskdusts** [comment]
谢谢大佬，我弄好了(●°u°●)​ 」

**Comment by isecret** [comment]
Happy coding~ : )
